#development version of configuration
server:
  port: 8084

  #database connections
spring:
  datasource:
    url: JDBC:mysql://localhost:3306/auth_db
    username: root
    password: Mandeep123

#    Hikari:
#     pool-name: HikariCP
#     maximum-pool-size: 5
#      connection-timeout: 10000
#      idle-timeout: 600000
#      max-lifetime: 1800000
#      validation-timeout: 1800000
#      leak-detection-threshold: 0
#     initialization-fail-timeout: -1

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialet
          format_sql: true
        show-sql: true



