#development version of configurations
server:
  port: 8084

#  database connections
spring:
  datasource:
    url: JDBC:mysql://localhost:3306/auth_db
    username: root
    password: Mandeep123

  #    hikari:
  #      pool-name: HikariCP
  #      maximum-pool-size: 5
  #      connection-timeout: 10000
  #      idle-timeout: 600000
  #      max-lifetime: 1800000
  #      validation-timeout: 1800000
  #      leak-detection-threshold: 0
  #      initialization-fail-timeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  security:
    #    oauth2 configurations
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:test-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:test-client-secret}
          #  redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #/login/oauth2/code/google
            scope:
              - email
              - profile
              - openid
          github:
            client-id: ${GITHUB_CLIENT_ID:test-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:test-client-secret}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            #/login/oauth2/code/github
            scope:
              - user:email
              - read:user

#    jpa and hibernate configurations


logging:
  level:
    org.springframework.security: DEBUG


security:
  jwt:
    secret: 1234567890123456789012345678901234567890123456789012345678901234
    issuer: api.mandeep.com
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:10}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:localhost}


app:
  cors:
    front-end-url: http://localhost:5173
  auth:
    frontend:
      success-redirect: http://localhost:5173/auth/success
      failure-redirect: http://localhost:5173/auth/failure
